chingu-voyage7/Bears-Team-02

- README.md
> 📝 Fix typo in README.md

- backend/datamodel.graphql
- backend/src/generated/index.d.ts
- backend/src/generated/index.js
- backend/src/generated/prisma-schema.js
- backend/src/generated/prisma.graphql
- change Library to array
- change Library enum values
- change Price to enum
> 🗃 update datamodel

- README.md
- backend/database/generateData.js
- backend/database/seed1.js
- backend/database/seed2.js
- backend/database/seed3.js
- backend/src/index.js
- backend/src/resolvers/Mutation.js
- backend/src/resolvers/Query.js
- backend/src/resolvers/fragments/UserWithReviews.js
- backend/src/resolvers/permissions/index.js
- backend/src/schema.graphql
- backend/src/services/passport.js
- cleans up sloppy code in the seeding scripts
- `passport` routing is now based on `process.env.NODE_ENV`
- moves CORS config to `applyMiddleware()`
- adds `.env` variables and descriptions to README
> Benjaminadk

- backend/src/services/passport.js
> :bug: Fix passport

- frontend/components/Signin.js
- frontend/components/Signup.js
> ✨User Signup and Signin in react

- frontend/components/About.js
- frontend/components/Header.js
- frontend/components/Nav.js
- frontend/components/Page.js
- frontend/components/Search.js
- frontend/package-lock.json
- frontend/pages/index.js
- package-lock.json
> ✨Create Header, links, and routes

- backend/package.json
- frontend/components/Header.js
- frontend/components/Page.js
- frontend/components/Posts.js
- frontend/components/Search.js
- frontend/components/Signin.js
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/index.js
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Incomplete/work-in-progress, PR is for discussion/feedback
- [ x] I have performed a self-review of my own code
- [ x ] There are no merge conflicts
> 📝 add search bar to posts component and take it from the header nav bar

- backend/database/generateData.js
- backend/database/seed2.js
- backend/package.json
- frontend/components/Header.js
- frontend/components/Posts.js
- frontend/components/Search.js
- frontend/lib/averageRating.js
- frontend/package.json
- frontend/styles/components/posts.scss
- Add very basic styling to posts returned from search query
- Add order by filtering and average rating function to posts component
- Filter: Most Reviewed is not yet implemented, it currently reverses the post array
- Expands the database seeding function, all contributors have the following creds by default
```
name: 'ben' || 'frank' || 'leen' || 'eric',
email: <name>@gmail.com,
password: 'password',
role: ADMIN
```
- Also adds 3 reviews x 25 posts for more realistic mock data
User tested multiple times
> Add order by & Add more reviews and admins to seed function

- frontend/components/Header.js
- frontend/components/InnerHeader.js
- frontend/components/Posts.js
- frontend/package-lock.json
- frontend/package.json
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback
- [ x] There are no merge conflicts
> 📝fix header/search

- frontend/components/Posts.js
- frontend/components/Signin.js
- frontend/styles/components/posts.scss
Adds the price filter to `/posts`.
Adds basic styling to Post component
- manual testing
> :sparkles: Add feature price filter

- frontend/components/Posts.js
- frontend/components/Signin.js
- frontend/styles/components/posts.scss
Wires up signin mutation and redirects user to homepage
> :bug: Fix bug in signin

- README.md
- frontend/styles/components/post.scss
- [ x] Complete, but not tested (may need new tests)
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
> 📝Fix img width and height on the post component and add Leen's linkedin link on READ.ME

- frontend/components/Posts.js
- frontend/styles/components/posts.scss
> :lipstick: Add Posts style

- frontend/components/Posts.js
- frontend/package-lock.json
- frontend/styles/components/posts.scss
> :lipstick: Add star component to Posts

- frontend/components/Post.js
- frontend/components/Review.js
- frontend/styles/abstracts/_variables.scss
- frontend/styles/components/post.scss
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
> :lipstick: improve post component styling

- frontend/components/Post.js
- frontend/styles/components/post.scss
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
> :lipstick: replace fire with stars

- frontend/components/Post.js
- frontend/styles/components/post.scss
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Incomplete/work-in-progress, PR is for discussion/feedback
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [ x] There are no merge conflicts
> :lipstick: update post component style

- frontend/components/Post1.js
- frontend/styles/components/post.scss
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback
- [x ] My code follows the style guidelines of this project
- [ x] My changes generate no new warnings
> :bug: fix review-button

- frontend/components/Profile.js
- frontend/components/Signin.js
- frontend/components/Signup.js
- frontend/styles/pages/signin.scss
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Incomplete/work-in-progress, PR is for discussion/feedback
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
> :lipstick: fix gap between the title and form

- backend/package-lock.json
- frontend/components/Home.js
- frontend/components/LandingSearch.js
- frontend/styles/components/landingsearch.scss
- frontend/styles/main.scss
> :tractor: :lipstick: add search box and add some styleing.
